In [1]:
#Exp_no:5

In [2]:
#Name:Tanisha S Gour
#Roll no:71
#Sec:B
#Subject:ET1
#Date:21/8/2025

In [3]:
#Aim: Creation of arrays using numpy

In [1]:
import numpy as np

In [2]:
#creating 1D array using numpy

In [3]:
a1=np.array([10,20,30,40,50])

In [4]:
a1

array([10, 20, 30, 40, 50])

In [5]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [6]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [7]:
#creating 2D array using matrix

In [8]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
